### ISSUE TITLE
unmatched tags

### ISSUE THREAD

**Issue by printercu** [Platron/payment_params_templates#1]
waiter_asinchrone has 2 html tags, one of them is not closed.

``` html
<!doctype html>
<html>
    <html xmlns="http://www.w3.org/1999/xhtml">
```

**Comment by lashnag** [comment]
Fixed

**Comment by printercu** [comment]
Не хотите перевести все на использование шаблонизатора?
Посмотрите https://github.com/printercu/card_payment_template
- 1 исходник для всех языков, переводы хранятся отдельно
- в шаблоне можно писать логику и рендерить его по разному для релиза/тестирования (вместо `_local`)
- не нужно следить за закрывающими тегами
- можно дописывать функции хэлперы (для отображения суммы с картинкой валюты, например)
- выносить общие части в отдельный файл (хедер с инфо о заказе).
- хтмл файлы все так же остаются в репозитории

**Comment by lashnag** [comment]
Проект Платрон написал с использованием собственного шаблонизатора. Поэтому замена его на шаблонизатор типа twig/smarty предусматривает огромное количество изменений в системе.
1. Переводы каждого мерчанта придется хранить в отдельном Language файле
2. Шаблон представлен в максимально простой форме _local. Для работы не надо ни веб сервера, ни php. Это позволяет править шаблон только верстальщику без знания php или выкачивания всего проекта с шаблонизатором и запуском его

> Понедельник, 10 октября 2016, 15:08 +03:00 от printercu notifications@github.com:
> 
> Не хотите перевести все на использование шаблонизатора?
> Посмотрите  https://github.com/printercu/card_payment_template
> -  1 исходник для всех языков, переводы хранятся отдельно
> -  в шаблоне можно писать логику и рендерить его по разному для релиза/тестирования (вместо _local)
> -  не нужно следить за закрывающими тегами
> -  можно дописывать функции хэлперы (для отображения суммы с картинкой валюты, например)
> -  выносить общие части в отдельный файл (хедер с инфо о заказе).
>   —
>   You are receiving this because you modified the open/close state.
>   Reply to this email directly,  view it on GitHub , or  mute the thread .

С уважением, Лашнев Алексей

**Comment by printercu** [comment]
Я не предлагаю вам менять внутреннюю систему шаблонизации. Посмотрите репозиторий - это шаблоны из Platron/payment_params_templates. Вам все так же будут присылать html файлы с вашими собственными тегами.

Еще некоторые плюсы предлагаемого варианта:
- При правке шаблона он правится во всех языках. Не нужно копипасты.
- Тоже про _local файлы. (Сейчас в waiter_asinchrone нет места под лого, в его _local версии есть).

Вот ещё места, где набор классов разный (может оно так и задумано, но имо сбивает с толку, "а какой вариант правильный"):
- https://github.com/Platron/payment_params_templates/blob/master/www/payment_params_templates/%7B%7Bcustomization_merchant_id%7D%7D/ru/payment_params_local.html#L323 (`ps_additional_field js_ps_additional_field`)
- https://github.com/Platron/payment_params_templates/blob/master/www/payment_params_templates/%7B%7Bcustomization_merchant_id%7D%7D/ru/payment_params.html#L258 (`form_item ps_additional_field form_item js_ps_additional_field`)

**Comment by lashnag** [comment]
Про различные классы - в шаблонах все правильно. Платежные системы и некоторые классы добавляются динамически. Файл _local нужен для примера оформления
Про правки шаблона в разных языках - опять же повторюсь, сделано было для того, чтобы можно было найти только верстальщика для верстки
Про лого - так сделано и в остальных шаблонах. Логотип есть только в _local. В описании есть строки про логотип

> Понедельник, 10 октября 2016, 18:17 +03:00 от printercu notifications@github.com:
> 
> Я не предлагаю вам менять внутреннюю систему шаблонизации. Посмотрите репозиторий - это шаблоны из Platron/payment_params_templates. Вам все так же будут присылать html файлы с вашими собственными тегами.
> Еще некоторые плюсы предлагаемого варианта:
> -  При правке шаблона он правится во всех языках. Не нужно копипасты.
> -  Тоже про _local файлы. (Сейчас в waiter_asinchrone нет места под лого, в его _local версии есть).
>   Вот ещё места, где набор классов разный (может оно так и задумано, но имо сбивает с толку "а какой вариант правильный"):
> -  https://github.com/Platron/payment_params_templates/blob/master/www/payment_params_templates/%7B%7Bcustomization_merchant_id%7D%7D/ru/payment_params_local.html#L323 (ps_additional_field js_ps_additional_field)
> -  https://github.com/Platron/payment_params_templates/blob/master/www/payment_params_templates/%7B%7Bcustomization_merchant_id%7D%7D/ru/payment_params.html#L258 (form_item ps_additional_field form_item js_ps_additional_field)
>   —
>   You are receiving this because you modified the open/close state.
>   Reply to this email directly,  view it on GitHub , or  mute the thread .

С уважением, Лашнев Алексей
